# Generated by Django 5.1.3 on 2025-04-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fault_cases',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Warning', 'Warning'), ('Fault', 'Fault')], default='OK', max_length=7)),
                ('importance_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Technician', 'Technician'), ('Repair', 'Repair'), ('Manager', 'Manager'), ('ViewOnly', 'ViewOnly')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FaultNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fault_case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faultcase')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'db_table': 'fault_notes',
            },
        ),
        migrations.CreateModel(
            name='FaultNoteImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fault_note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faultnote')),
            ],
            options={
                'db_table': 'fault_note_images',
            },
        ),
        migrations.AddField(
            model_name='faultcase',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine'),
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_role', models.CharField(choices=[('Technician', 'Technician'), ('Repair', 'Repair')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='myapp.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.user')),
            ],
            options={
                'db_table': 'machine_assignments',
            },
        ),
        migrations.CreateModel(
            name='FaultComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('fault_case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faultcase')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'db_table': 'fault_comments',
            },
        ),
        migrations.AddField(
            model_name='faultcase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warning_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
            options={
                'db_table': 'warnings',
            },
        ),
    ]
